// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/jwblangley/neat/proto/evolution.proto

package jwblangley.neat.proto;

public final class EvolutionOuterClass {
  private EvolutionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EvolutionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jwblangley.neat.proto.Evolution)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    java.util.List<jwblangley.neat.proto.Genotypes.NetworkGenotype> 
        getCurrentGenerationList();
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    jwblangley.neat.proto.Genotypes.NetworkGenotype getCurrentGeneration(int index);
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    int getCurrentGenerationCount();
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    java.util.List<? extends jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder> 
        getCurrentGenerationOrBuilderList();
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder getCurrentGenerationOrBuilder(
        int index);

    /**
     * <code>int32 generationNumber = 2;</code>
     * @return The generationNumber.
     */
    int getGenerationNumber();

    /**
     * <code>int32 currentInnovationMarker = 3;</code>
     * @return The currentInnovationMarker.
     */
    int getCurrentInnovationMarker();

    /**
     * <code>double compatibilityDistanceThreshold = 4;</code>
     * @return The compatibilityDistanceThreshold.
     */
    double getCompatibilityDistanceThreshold();
  }
  /**
   * Protobuf type {@code jwblangley.neat.proto.Evolution}
   */
  public static final class Evolution extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jwblangley.neat.proto.Evolution)
      EvolutionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Evolution.newBuilder() to construct.
    private Evolution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Evolution() {
      currentGeneration_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Evolution();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Evolution(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                currentGeneration_ = new java.util.ArrayList<jwblangley.neat.proto.Genotypes.NetworkGenotype>();
                mutable_bitField0_ |= 0x00000001;
              }
              currentGeneration_.add(
                  input.readMessage(jwblangley.neat.proto.Genotypes.NetworkGenotype.parser(), extensionRegistry));
              break;
            }
            case 16: {

              generationNumber_ = input.readInt32();
              break;
            }
            case 24: {

              currentInnovationMarker_ = input.readInt32();
              break;
            }
            case 33: {

              compatibilityDistanceThreshold_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          currentGeneration_ = java.util.Collections.unmodifiableList(currentGeneration_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jwblangley.neat.proto.EvolutionOuterClass.internal_static_jwblangley_neat_proto_Evolution_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jwblangley.neat.proto.EvolutionOuterClass.internal_static_jwblangley_neat_proto_Evolution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jwblangley.neat.proto.EvolutionOuterClass.Evolution.class, jwblangley.neat.proto.EvolutionOuterClass.Evolution.Builder.class);
    }

    public static final int CURRENTGENERATION_FIELD_NUMBER = 1;
    private java.util.List<jwblangley.neat.proto.Genotypes.NetworkGenotype> currentGeneration_;
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    @java.lang.Override
    public java.util.List<jwblangley.neat.proto.Genotypes.NetworkGenotype> getCurrentGenerationList() {
      return currentGeneration_;
    }
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder> 
        getCurrentGenerationOrBuilderList() {
      return currentGeneration_;
    }
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    @java.lang.Override
    public int getCurrentGenerationCount() {
      return currentGeneration_.size();
    }
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.NetworkGenotype getCurrentGeneration(int index) {
      return currentGeneration_.get(index);
    }
    /**
     * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
     */
    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder getCurrentGenerationOrBuilder(
        int index) {
      return currentGeneration_.get(index);
    }

    public static final int GENERATIONNUMBER_FIELD_NUMBER = 2;
    private int generationNumber_;
    /**
     * <code>int32 generationNumber = 2;</code>
     * @return The generationNumber.
     */
    @java.lang.Override
    public int getGenerationNumber() {
      return generationNumber_;
    }

    public static final int CURRENTINNOVATIONMARKER_FIELD_NUMBER = 3;
    private int currentInnovationMarker_;
    /**
     * <code>int32 currentInnovationMarker = 3;</code>
     * @return The currentInnovationMarker.
     */
    @java.lang.Override
    public int getCurrentInnovationMarker() {
      return currentInnovationMarker_;
    }

    public static final int COMPATIBILITYDISTANCETHRESHOLD_FIELD_NUMBER = 4;
    private double compatibilityDistanceThreshold_;
    /**
     * <code>double compatibilityDistanceThreshold = 4;</code>
     * @return The compatibilityDistanceThreshold.
     */
    @java.lang.Override
    public double getCompatibilityDistanceThreshold() {
      return compatibilityDistanceThreshold_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < currentGeneration_.size(); i++) {
        output.writeMessage(1, currentGeneration_.get(i));
      }
      if (generationNumber_ != 0) {
        output.writeInt32(2, generationNumber_);
      }
      if (currentInnovationMarker_ != 0) {
        output.writeInt32(3, currentInnovationMarker_);
      }
      if (compatibilityDistanceThreshold_ != 0D) {
        output.writeDouble(4, compatibilityDistanceThreshold_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < currentGeneration_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, currentGeneration_.get(i));
      }
      if (generationNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, generationNumber_);
      }
      if (currentInnovationMarker_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, currentInnovationMarker_);
      }
      if (compatibilityDistanceThreshold_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, compatibilityDistanceThreshold_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jwblangley.neat.proto.EvolutionOuterClass.Evolution)) {
        return super.equals(obj);
      }
      jwblangley.neat.proto.EvolutionOuterClass.Evolution other = (jwblangley.neat.proto.EvolutionOuterClass.Evolution) obj;

      if (!getCurrentGenerationList()
          .equals(other.getCurrentGenerationList())) return false;
      if (getGenerationNumber()
          != other.getGenerationNumber()) return false;
      if (getCurrentInnovationMarker()
          != other.getCurrentInnovationMarker()) return false;
      if (java.lang.Double.doubleToLongBits(getCompatibilityDistanceThreshold())
          != java.lang.Double.doubleToLongBits(
              other.getCompatibilityDistanceThreshold())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCurrentGenerationCount() > 0) {
        hash = (37 * hash) + CURRENTGENERATION_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentGenerationList().hashCode();
      }
      hash = (37 * hash) + GENERATIONNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getGenerationNumber();
      hash = (37 * hash) + CURRENTINNOVATIONMARKER_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentInnovationMarker();
      hash = (37 * hash) + COMPATIBILITYDISTANCETHRESHOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCompatibilityDistanceThreshold()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jwblangley.neat.proto.EvolutionOuterClass.Evolution prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jwblangley.neat.proto.Evolution}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jwblangley.neat.proto.Evolution)
        jwblangley.neat.proto.EvolutionOuterClass.EvolutionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jwblangley.neat.proto.EvolutionOuterClass.internal_static_jwblangley_neat_proto_Evolution_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jwblangley.neat.proto.EvolutionOuterClass.internal_static_jwblangley_neat_proto_Evolution_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jwblangley.neat.proto.EvolutionOuterClass.Evolution.class, jwblangley.neat.proto.EvolutionOuterClass.Evolution.Builder.class);
      }

      // Construct using jwblangley.neat.proto.EvolutionOuterClass.Evolution.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCurrentGenerationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (currentGenerationBuilder_ == null) {
          currentGeneration_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          currentGenerationBuilder_.clear();
        }
        generationNumber_ = 0;

        currentInnovationMarker_ = 0;

        compatibilityDistanceThreshold_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jwblangley.neat.proto.EvolutionOuterClass.internal_static_jwblangley_neat_proto_Evolution_descriptor;
      }

      @java.lang.Override
      public jwblangley.neat.proto.EvolutionOuterClass.Evolution getDefaultInstanceForType() {
        return jwblangley.neat.proto.EvolutionOuterClass.Evolution.getDefaultInstance();
      }

      @java.lang.Override
      public jwblangley.neat.proto.EvolutionOuterClass.Evolution build() {
        jwblangley.neat.proto.EvolutionOuterClass.Evolution result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jwblangley.neat.proto.EvolutionOuterClass.Evolution buildPartial() {
        jwblangley.neat.proto.EvolutionOuterClass.Evolution result = new jwblangley.neat.proto.EvolutionOuterClass.Evolution(this);
        int from_bitField0_ = bitField0_;
        if (currentGenerationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            currentGeneration_ = java.util.Collections.unmodifiableList(currentGeneration_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.currentGeneration_ = currentGeneration_;
        } else {
          result.currentGeneration_ = currentGenerationBuilder_.build();
        }
        result.generationNumber_ = generationNumber_;
        result.currentInnovationMarker_ = currentInnovationMarker_;
        result.compatibilityDistanceThreshold_ = compatibilityDistanceThreshold_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jwblangley.neat.proto.EvolutionOuterClass.Evolution) {
          return mergeFrom((jwblangley.neat.proto.EvolutionOuterClass.Evolution)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jwblangley.neat.proto.EvolutionOuterClass.Evolution other) {
        if (other == jwblangley.neat.proto.EvolutionOuterClass.Evolution.getDefaultInstance()) return this;
        if (currentGenerationBuilder_ == null) {
          if (!other.currentGeneration_.isEmpty()) {
            if (currentGeneration_.isEmpty()) {
              currentGeneration_ = other.currentGeneration_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCurrentGenerationIsMutable();
              currentGeneration_.addAll(other.currentGeneration_);
            }
            onChanged();
          }
        } else {
          if (!other.currentGeneration_.isEmpty()) {
            if (currentGenerationBuilder_.isEmpty()) {
              currentGenerationBuilder_.dispose();
              currentGenerationBuilder_ = null;
              currentGeneration_ = other.currentGeneration_;
              bitField0_ = (bitField0_ & ~0x00000001);
              currentGenerationBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCurrentGenerationFieldBuilder() : null;
            } else {
              currentGenerationBuilder_.addAllMessages(other.currentGeneration_);
            }
          }
        }
        if (other.getGenerationNumber() != 0) {
          setGenerationNumber(other.getGenerationNumber());
        }
        if (other.getCurrentInnovationMarker() != 0) {
          setCurrentInnovationMarker(other.getCurrentInnovationMarker());
        }
        if (other.getCompatibilityDistanceThreshold() != 0D) {
          setCompatibilityDistanceThreshold(other.getCompatibilityDistanceThreshold());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jwblangley.neat.proto.EvolutionOuterClass.Evolution parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jwblangley.neat.proto.EvolutionOuterClass.Evolution) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<jwblangley.neat.proto.Genotypes.NetworkGenotype> currentGeneration_ =
        java.util.Collections.emptyList();
      private void ensureCurrentGenerationIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          currentGeneration_ = new java.util.ArrayList<jwblangley.neat.proto.Genotypes.NetworkGenotype>(currentGeneration_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          jwblangley.neat.proto.Genotypes.NetworkGenotype, jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder, jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder> currentGenerationBuilder_;

      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public java.util.List<jwblangley.neat.proto.Genotypes.NetworkGenotype> getCurrentGenerationList() {
        if (currentGenerationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(currentGeneration_);
        } else {
          return currentGenerationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public int getCurrentGenerationCount() {
        if (currentGenerationBuilder_ == null) {
          return currentGeneration_.size();
        } else {
          return currentGenerationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NetworkGenotype getCurrentGeneration(int index) {
        if (currentGenerationBuilder_ == null) {
          return currentGeneration_.get(index);
        } else {
          return currentGenerationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder setCurrentGeneration(
          int index, jwblangley.neat.proto.Genotypes.NetworkGenotype value) {
        if (currentGenerationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrentGenerationIsMutable();
          currentGeneration_.set(index, value);
          onChanged();
        } else {
          currentGenerationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder setCurrentGeneration(
          int index, jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder builderForValue) {
        if (currentGenerationBuilder_ == null) {
          ensureCurrentGenerationIsMutable();
          currentGeneration_.set(index, builderForValue.build());
          onChanged();
        } else {
          currentGenerationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder addCurrentGeneration(jwblangley.neat.proto.Genotypes.NetworkGenotype value) {
        if (currentGenerationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrentGenerationIsMutable();
          currentGeneration_.add(value);
          onChanged();
        } else {
          currentGenerationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder addCurrentGeneration(
          int index, jwblangley.neat.proto.Genotypes.NetworkGenotype value) {
        if (currentGenerationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrentGenerationIsMutable();
          currentGeneration_.add(index, value);
          onChanged();
        } else {
          currentGenerationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder addCurrentGeneration(
          jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder builderForValue) {
        if (currentGenerationBuilder_ == null) {
          ensureCurrentGenerationIsMutable();
          currentGeneration_.add(builderForValue.build());
          onChanged();
        } else {
          currentGenerationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder addCurrentGeneration(
          int index, jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder builderForValue) {
        if (currentGenerationBuilder_ == null) {
          ensureCurrentGenerationIsMutable();
          currentGeneration_.add(index, builderForValue.build());
          onChanged();
        } else {
          currentGenerationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder addAllCurrentGeneration(
          java.lang.Iterable<? extends jwblangley.neat.proto.Genotypes.NetworkGenotype> values) {
        if (currentGenerationBuilder_ == null) {
          ensureCurrentGenerationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, currentGeneration_);
          onChanged();
        } else {
          currentGenerationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder clearCurrentGeneration() {
        if (currentGenerationBuilder_ == null) {
          currentGeneration_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          currentGenerationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public Builder removeCurrentGeneration(int index) {
        if (currentGenerationBuilder_ == null) {
          ensureCurrentGenerationIsMutable();
          currentGeneration_.remove(index);
          onChanged();
        } else {
          currentGenerationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder getCurrentGenerationBuilder(
          int index) {
        return getCurrentGenerationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder getCurrentGenerationOrBuilder(
          int index) {
        if (currentGenerationBuilder_ == null) {
          return currentGeneration_.get(index);  } else {
          return currentGenerationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public java.util.List<? extends jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder> 
           getCurrentGenerationOrBuilderList() {
        if (currentGenerationBuilder_ != null) {
          return currentGenerationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(currentGeneration_);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder addCurrentGenerationBuilder() {
        return getCurrentGenerationFieldBuilder().addBuilder(
            jwblangley.neat.proto.Genotypes.NetworkGenotype.getDefaultInstance());
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder addCurrentGenerationBuilder(
          int index) {
        return getCurrentGenerationFieldBuilder().addBuilder(
            index, jwblangley.neat.proto.Genotypes.NetworkGenotype.getDefaultInstance());
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NetworkGenotype currentGeneration = 1;</code>
       */
      public java.util.List<jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder> 
           getCurrentGenerationBuilderList() {
        return getCurrentGenerationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          jwblangley.neat.proto.Genotypes.NetworkGenotype, jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder, jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder> 
          getCurrentGenerationFieldBuilder() {
        if (currentGenerationBuilder_ == null) {
          currentGenerationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              jwblangley.neat.proto.Genotypes.NetworkGenotype, jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder, jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder>(
                  currentGeneration_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          currentGeneration_ = null;
        }
        return currentGenerationBuilder_;
      }

      private int generationNumber_ ;
      /**
       * <code>int32 generationNumber = 2;</code>
       * @return The generationNumber.
       */
      @java.lang.Override
      public int getGenerationNumber() {
        return generationNumber_;
      }
      /**
       * <code>int32 generationNumber = 2;</code>
       * @param value The generationNumber to set.
       * @return This builder for chaining.
       */
      public Builder setGenerationNumber(int value) {
        
        generationNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 generationNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenerationNumber() {
        
        generationNumber_ = 0;
        onChanged();
        return this;
      }

      private int currentInnovationMarker_ ;
      /**
       * <code>int32 currentInnovationMarker = 3;</code>
       * @return The currentInnovationMarker.
       */
      @java.lang.Override
      public int getCurrentInnovationMarker() {
        return currentInnovationMarker_;
      }
      /**
       * <code>int32 currentInnovationMarker = 3;</code>
       * @param value The currentInnovationMarker to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentInnovationMarker(int value) {
        
        currentInnovationMarker_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentInnovationMarker = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentInnovationMarker() {
        
        currentInnovationMarker_ = 0;
        onChanged();
        return this;
      }

      private double compatibilityDistanceThreshold_ ;
      /**
       * <code>double compatibilityDistanceThreshold = 4;</code>
       * @return The compatibilityDistanceThreshold.
       */
      @java.lang.Override
      public double getCompatibilityDistanceThreshold() {
        return compatibilityDistanceThreshold_;
      }
      /**
       * <code>double compatibilityDistanceThreshold = 4;</code>
       * @param value The compatibilityDistanceThreshold to set.
       * @return This builder for chaining.
       */
      public Builder setCompatibilityDistanceThreshold(double value) {
        
        compatibilityDistanceThreshold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double compatibilityDistanceThreshold = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompatibilityDistanceThreshold() {
        
        compatibilityDistanceThreshold_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jwblangley.neat.proto.Evolution)
    }

    // @@protoc_insertion_point(class_scope:jwblangley.neat.proto.Evolution)
    private static final jwblangley.neat.proto.EvolutionOuterClass.Evolution DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jwblangley.neat.proto.EvolutionOuterClass.Evolution();
    }

    public static jwblangley.neat.proto.EvolutionOuterClass.Evolution getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Evolution>
        PARSER = new com.google.protobuf.AbstractParser<Evolution>() {
      @java.lang.Override
      public Evolution parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Evolution(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Evolution> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Evolution> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jwblangley.neat.proto.EvolutionOuterClass.Evolution getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jwblangley_neat_proto_Evolution_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jwblangley_neat_proto_Evolution_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/jwblangley/neat/proto/evolution.pr" +
      "oto\022\025jwblangley.neat.proto\032)src/jwblangl" +
      "ey/neat/proto/genotypes.proto\"\261\001\n\tEvolut" +
      "ion\022A\n\021currentGeneration\030\001 \003(\0132&.jwblang" +
      "ley.neat.proto.NetworkGenotype\022\030\n\020genera" +
      "tionNumber\030\002 \001(\005\022\037\n\027currentInnovationMar" +
      "ker\030\003 \001(\005\022&\n\036compatibilityDistanceThresh" +
      "old\030\004 \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          jwblangley.neat.proto.Genotypes.getDescriptor(),
        });
    internal_static_jwblangley_neat_proto_Evolution_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jwblangley_neat_proto_Evolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jwblangley_neat_proto_Evolution_descriptor,
        new java.lang.String[] { "CurrentGeneration", "GenerationNumber", "CurrentInnovationMarker", "CompatibilityDistanceThreshold", });
    jwblangley.neat.proto.Genotypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
