// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/jwblangley/neat/proto/genotypes.proto

package jwblangley.neat.proto;

public final class Genotypes {
  private Genotypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetworkGenotypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jwblangley.neat.proto.NetworkGenotype)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    java.util.List<jwblangley.neat.proto.Genotypes.NeuronGenotype> 
        getNeuronsList();
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    jwblangley.neat.proto.Genotypes.NeuronGenotype getNeurons(int index);
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    int getNeuronsCount();
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    java.util.List<? extends jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder> 
        getNeuronsOrBuilderList();
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder getNeuronsOrBuilder(
        int index);

    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    java.util.List<jwblangley.neat.proto.Genotypes.ConnectionGenotype> 
        getConnectionsList();
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    jwblangley.neat.proto.Genotypes.ConnectionGenotype getConnections(int index);
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    int getConnectionsCount();
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    java.util.List<? extends jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder> 
        getConnectionsOrBuilderList();
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder getConnectionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code jwblangley.neat.proto.NetworkGenotype}
   */
  public static final class NetworkGenotype extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jwblangley.neat.proto.NetworkGenotype)
      NetworkGenotypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetworkGenotype.newBuilder() to construct.
    private NetworkGenotype(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkGenotype() {
      neurons_ = java.util.Collections.emptyList();
      connections_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetworkGenotype();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetworkGenotype(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                neurons_ = new java.util.ArrayList<jwblangley.neat.proto.Genotypes.NeuronGenotype>();
                mutable_bitField0_ |= 0x00000001;
              }
              neurons_.add(
                  input.readMessage(jwblangley.neat.proto.Genotypes.NeuronGenotype.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                connections_ = new java.util.ArrayList<jwblangley.neat.proto.Genotypes.ConnectionGenotype>();
                mutable_bitField0_ |= 0x00000002;
              }
              connections_.add(
                  input.readMessage(jwblangley.neat.proto.Genotypes.ConnectionGenotype.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          neurons_ = java.util.Collections.unmodifiableList(neurons_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          connections_ = java.util.Collections.unmodifiableList(connections_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NetworkGenotype_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NetworkGenotype_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jwblangley.neat.proto.Genotypes.NetworkGenotype.class, jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder.class);
    }

    public static final int NEURONS_FIELD_NUMBER = 1;
    private java.util.List<jwblangley.neat.proto.Genotypes.NeuronGenotype> neurons_;
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    @java.lang.Override
    public java.util.List<jwblangley.neat.proto.Genotypes.NeuronGenotype> getNeuronsList() {
      return neurons_;
    }
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder> 
        getNeuronsOrBuilderList() {
      return neurons_;
    }
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    @java.lang.Override
    public int getNeuronsCount() {
      return neurons_.size();
    }
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.NeuronGenotype getNeurons(int index) {
      return neurons_.get(index);
    }
    /**
     * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
     */
    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder getNeuronsOrBuilder(
        int index) {
      return neurons_.get(index);
    }

    public static final int CONNECTIONS_FIELD_NUMBER = 2;
    private java.util.List<jwblangley.neat.proto.Genotypes.ConnectionGenotype> connections_;
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    @java.lang.Override
    public java.util.List<jwblangley.neat.proto.Genotypes.ConnectionGenotype> getConnectionsList() {
      return connections_;
    }
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder> 
        getConnectionsOrBuilderList() {
      return connections_;
    }
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    @java.lang.Override
    public int getConnectionsCount() {
      return connections_.size();
    }
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.ConnectionGenotype getConnections(int index) {
      return connections_.get(index);
    }
    /**
     * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
     */
    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder getConnectionsOrBuilder(
        int index) {
      return connections_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < neurons_.size(); i++) {
        output.writeMessage(1, neurons_.get(i));
      }
      for (int i = 0; i < connections_.size(); i++) {
        output.writeMessage(2, connections_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < neurons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, neurons_.get(i));
      }
      for (int i = 0; i < connections_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, connections_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jwblangley.neat.proto.Genotypes.NetworkGenotype)) {
        return super.equals(obj);
      }
      jwblangley.neat.proto.Genotypes.NetworkGenotype other = (jwblangley.neat.proto.Genotypes.NetworkGenotype) obj;

      if (!getNeuronsList()
          .equals(other.getNeuronsList())) return false;
      if (!getConnectionsList()
          .equals(other.getConnectionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNeuronsCount() > 0) {
        hash = (37 * hash) + NEURONS_FIELD_NUMBER;
        hash = (53 * hash) + getNeuronsList().hashCode();
      }
      if (getConnectionsCount() > 0) {
        hash = (37 * hash) + CONNECTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getConnectionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.NetworkGenotype parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jwblangley.neat.proto.Genotypes.NetworkGenotype prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jwblangley.neat.proto.NetworkGenotype}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jwblangley.neat.proto.NetworkGenotype)
        jwblangley.neat.proto.Genotypes.NetworkGenotypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NetworkGenotype_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NetworkGenotype_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jwblangley.neat.proto.Genotypes.NetworkGenotype.class, jwblangley.neat.proto.Genotypes.NetworkGenotype.Builder.class);
      }

      // Construct using jwblangley.neat.proto.Genotypes.NetworkGenotype.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNeuronsFieldBuilder();
          getConnectionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (neuronsBuilder_ == null) {
          neurons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          neuronsBuilder_.clear();
        }
        if (connectionsBuilder_ == null) {
          connections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          connectionsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NetworkGenotype_descriptor;
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.NetworkGenotype getDefaultInstanceForType() {
        return jwblangley.neat.proto.Genotypes.NetworkGenotype.getDefaultInstance();
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.NetworkGenotype build() {
        jwblangley.neat.proto.Genotypes.NetworkGenotype result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.NetworkGenotype buildPartial() {
        jwblangley.neat.proto.Genotypes.NetworkGenotype result = new jwblangley.neat.proto.Genotypes.NetworkGenotype(this);
        int from_bitField0_ = bitField0_;
        if (neuronsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            neurons_ = java.util.Collections.unmodifiableList(neurons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.neurons_ = neurons_;
        } else {
          result.neurons_ = neuronsBuilder_.build();
        }
        if (connectionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            connections_ = java.util.Collections.unmodifiableList(connections_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.connections_ = connections_;
        } else {
          result.connections_ = connectionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jwblangley.neat.proto.Genotypes.NetworkGenotype) {
          return mergeFrom((jwblangley.neat.proto.Genotypes.NetworkGenotype)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jwblangley.neat.proto.Genotypes.NetworkGenotype other) {
        if (other == jwblangley.neat.proto.Genotypes.NetworkGenotype.getDefaultInstance()) return this;
        if (neuronsBuilder_ == null) {
          if (!other.neurons_.isEmpty()) {
            if (neurons_.isEmpty()) {
              neurons_ = other.neurons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNeuronsIsMutable();
              neurons_.addAll(other.neurons_);
            }
            onChanged();
          }
        } else {
          if (!other.neurons_.isEmpty()) {
            if (neuronsBuilder_.isEmpty()) {
              neuronsBuilder_.dispose();
              neuronsBuilder_ = null;
              neurons_ = other.neurons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              neuronsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNeuronsFieldBuilder() : null;
            } else {
              neuronsBuilder_.addAllMessages(other.neurons_);
            }
          }
        }
        if (connectionsBuilder_ == null) {
          if (!other.connections_.isEmpty()) {
            if (connections_.isEmpty()) {
              connections_ = other.connections_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureConnectionsIsMutable();
              connections_.addAll(other.connections_);
            }
            onChanged();
          }
        } else {
          if (!other.connections_.isEmpty()) {
            if (connectionsBuilder_.isEmpty()) {
              connectionsBuilder_.dispose();
              connectionsBuilder_ = null;
              connections_ = other.connections_;
              bitField0_ = (bitField0_ & ~0x00000002);
              connectionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConnectionsFieldBuilder() : null;
            } else {
              connectionsBuilder_.addAllMessages(other.connections_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jwblangley.neat.proto.Genotypes.NetworkGenotype parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jwblangley.neat.proto.Genotypes.NetworkGenotype) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<jwblangley.neat.proto.Genotypes.NeuronGenotype> neurons_ =
        java.util.Collections.emptyList();
      private void ensureNeuronsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          neurons_ = new java.util.ArrayList<jwblangley.neat.proto.Genotypes.NeuronGenotype>(neurons_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          jwblangley.neat.proto.Genotypes.NeuronGenotype, jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder, jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder> neuronsBuilder_;

      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public java.util.List<jwblangley.neat.proto.Genotypes.NeuronGenotype> getNeuronsList() {
        if (neuronsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(neurons_);
        } else {
          return neuronsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public int getNeuronsCount() {
        if (neuronsBuilder_ == null) {
          return neurons_.size();
        } else {
          return neuronsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NeuronGenotype getNeurons(int index) {
        if (neuronsBuilder_ == null) {
          return neurons_.get(index);
        } else {
          return neuronsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder setNeurons(
          int index, jwblangley.neat.proto.Genotypes.NeuronGenotype value) {
        if (neuronsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNeuronsIsMutable();
          neurons_.set(index, value);
          onChanged();
        } else {
          neuronsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder setNeurons(
          int index, jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder builderForValue) {
        if (neuronsBuilder_ == null) {
          ensureNeuronsIsMutable();
          neurons_.set(index, builderForValue.build());
          onChanged();
        } else {
          neuronsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder addNeurons(jwblangley.neat.proto.Genotypes.NeuronGenotype value) {
        if (neuronsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNeuronsIsMutable();
          neurons_.add(value);
          onChanged();
        } else {
          neuronsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder addNeurons(
          int index, jwblangley.neat.proto.Genotypes.NeuronGenotype value) {
        if (neuronsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNeuronsIsMutable();
          neurons_.add(index, value);
          onChanged();
        } else {
          neuronsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder addNeurons(
          jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder builderForValue) {
        if (neuronsBuilder_ == null) {
          ensureNeuronsIsMutable();
          neurons_.add(builderForValue.build());
          onChanged();
        } else {
          neuronsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder addNeurons(
          int index, jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder builderForValue) {
        if (neuronsBuilder_ == null) {
          ensureNeuronsIsMutable();
          neurons_.add(index, builderForValue.build());
          onChanged();
        } else {
          neuronsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder addAllNeurons(
          java.lang.Iterable<? extends jwblangley.neat.proto.Genotypes.NeuronGenotype> values) {
        if (neuronsBuilder_ == null) {
          ensureNeuronsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, neurons_);
          onChanged();
        } else {
          neuronsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder clearNeurons() {
        if (neuronsBuilder_ == null) {
          neurons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          neuronsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public Builder removeNeurons(int index) {
        if (neuronsBuilder_ == null) {
          ensureNeuronsIsMutable();
          neurons_.remove(index);
          onChanged();
        } else {
          neuronsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder getNeuronsBuilder(
          int index) {
        return getNeuronsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder getNeuronsOrBuilder(
          int index) {
        if (neuronsBuilder_ == null) {
          return neurons_.get(index);  } else {
          return neuronsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public java.util.List<? extends jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder> 
           getNeuronsOrBuilderList() {
        if (neuronsBuilder_ != null) {
          return neuronsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(neurons_);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder addNeuronsBuilder() {
        return getNeuronsFieldBuilder().addBuilder(
            jwblangley.neat.proto.Genotypes.NeuronGenotype.getDefaultInstance());
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder addNeuronsBuilder(
          int index) {
        return getNeuronsFieldBuilder().addBuilder(
            index, jwblangley.neat.proto.Genotypes.NeuronGenotype.getDefaultInstance());
      }
      /**
       * <code>repeated .jwblangley.neat.proto.NeuronGenotype neurons = 1;</code>
       */
      public java.util.List<jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder> 
           getNeuronsBuilderList() {
        return getNeuronsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          jwblangley.neat.proto.Genotypes.NeuronGenotype, jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder, jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder> 
          getNeuronsFieldBuilder() {
        if (neuronsBuilder_ == null) {
          neuronsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              jwblangley.neat.proto.Genotypes.NeuronGenotype, jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder, jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder>(
                  neurons_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          neurons_ = null;
        }
        return neuronsBuilder_;
      }

      private java.util.List<jwblangley.neat.proto.Genotypes.ConnectionGenotype> connections_ =
        java.util.Collections.emptyList();
      private void ensureConnectionsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          connections_ = new java.util.ArrayList<jwblangley.neat.proto.Genotypes.ConnectionGenotype>(connections_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          jwblangley.neat.proto.Genotypes.ConnectionGenotype, jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder, jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder> connectionsBuilder_;

      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public java.util.List<jwblangley.neat.proto.Genotypes.ConnectionGenotype> getConnectionsList() {
        if (connectionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(connections_);
        } else {
          return connectionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public int getConnectionsCount() {
        if (connectionsBuilder_ == null) {
          return connections_.size();
        } else {
          return connectionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public jwblangley.neat.proto.Genotypes.ConnectionGenotype getConnections(int index) {
        if (connectionsBuilder_ == null) {
          return connections_.get(index);
        } else {
          return connectionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder setConnections(
          int index, jwblangley.neat.proto.Genotypes.ConnectionGenotype value) {
        if (connectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectionsIsMutable();
          connections_.set(index, value);
          onChanged();
        } else {
          connectionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder setConnections(
          int index, jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder builderForValue) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          connections_.set(index, builderForValue.build());
          onChanged();
        } else {
          connectionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder addConnections(jwblangley.neat.proto.Genotypes.ConnectionGenotype value) {
        if (connectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectionsIsMutable();
          connections_.add(value);
          onChanged();
        } else {
          connectionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder addConnections(
          int index, jwblangley.neat.proto.Genotypes.ConnectionGenotype value) {
        if (connectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectionsIsMutable();
          connections_.add(index, value);
          onChanged();
        } else {
          connectionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder addConnections(
          jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder builderForValue) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          connections_.add(builderForValue.build());
          onChanged();
        } else {
          connectionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder addConnections(
          int index, jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder builderForValue) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          connections_.add(index, builderForValue.build());
          onChanged();
        } else {
          connectionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder addAllConnections(
          java.lang.Iterable<? extends jwblangley.neat.proto.Genotypes.ConnectionGenotype> values) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, connections_);
          onChanged();
        } else {
          connectionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder clearConnections() {
        if (connectionsBuilder_ == null) {
          connections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          connectionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public Builder removeConnections(int index) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          connections_.remove(index);
          onChanged();
        } else {
          connectionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder getConnectionsBuilder(
          int index) {
        return getConnectionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder getConnectionsOrBuilder(
          int index) {
        if (connectionsBuilder_ == null) {
          return connections_.get(index);  } else {
          return connectionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public java.util.List<? extends jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder> 
           getConnectionsOrBuilderList() {
        if (connectionsBuilder_ != null) {
          return connectionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(connections_);
        }
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder addConnectionsBuilder() {
        return getConnectionsFieldBuilder().addBuilder(
            jwblangley.neat.proto.Genotypes.ConnectionGenotype.getDefaultInstance());
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder addConnectionsBuilder(
          int index) {
        return getConnectionsFieldBuilder().addBuilder(
            index, jwblangley.neat.proto.Genotypes.ConnectionGenotype.getDefaultInstance());
      }
      /**
       * <code>repeated .jwblangley.neat.proto.ConnectionGenotype connections = 2;</code>
       */
      public java.util.List<jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder> 
           getConnectionsBuilderList() {
        return getConnectionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          jwblangley.neat.proto.Genotypes.ConnectionGenotype, jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder, jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder> 
          getConnectionsFieldBuilder() {
        if (connectionsBuilder_ == null) {
          connectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              jwblangley.neat.proto.Genotypes.ConnectionGenotype, jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder, jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder>(
                  connections_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          connections_ = null;
        }
        return connectionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jwblangley.neat.proto.NetworkGenotype)
    }

    // @@protoc_insertion_point(class_scope:jwblangley.neat.proto.NetworkGenotype)
    private static final jwblangley.neat.proto.Genotypes.NetworkGenotype DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jwblangley.neat.proto.Genotypes.NetworkGenotype();
    }

    public static jwblangley.neat.proto.Genotypes.NetworkGenotype getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetworkGenotype>
        PARSER = new com.google.protobuf.AbstractParser<NetworkGenotype>() {
      @java.lang.Override
      public NetworkGenotype parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetworkGenotype(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetworkGenotype> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkGenotype> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.NetworkGenotype getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NeuronGenotypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jwblangley.neat.proto.NeuronGenotype)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 uid = 1;</code>
     * @return The uid.
     */
    int getUid();

    /**
     * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
     * @return The enum numeric value on the wire for layer.
     */
    int getLayerValue();
    /**
     * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
     * @return The layer.
     */
    jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer getLayer();
  }
  /**
   * Protobuf type {@code jwblangley.neat.proto.NeuronGenotype}
   */
  public static final class NeuronGenotype extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jwblangley.neat.proto.NeuronGenotype)
      NeuronGenotypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NeuronGenotype.newBuilder() to construct.
    private NeuronGenotype(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NeuronGenotype() {
      layer_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NeuronGenotype();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NeuronGenotype(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              layer_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NeuronGenotype_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NeuronGenotype_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jwblangley.neat.proto.Genotypes.NeuronGenotype.class, jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder.class);
    }

    /**
     * Protobuf enum {@code jwblangley.neat.proto.NeuronGenotype.NeuronLayer}
     */
    public enum NeuronLayer
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INPUT = 0;</code>
       */
      INPUT(0),
      /**
       * <code>HIDDEN = 1;</code>
       */
      HIDDEN(1),
      /**
       * <code>OUTPUT = 2;</code>
       */
      OUTPUT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>INPUT = 0;</code>
       */
      public static final int INPUT_VALUE = 0;
      /**
       * <code>HIDDEN = 1;</code>
       */
      public static final int HIDDEN_VALUE = 1;
      /**
       * <code>OUTPUT = 2;</code>
       */
      public static final int OUTPUT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NeuronLayer valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static NeuronLayer forNumber(int value) {
        switch (value) {
          case 0: return INPUT;
          case 1: return HIDDEN;
          case 2: return OUTPUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NeuronLayer>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NeuronLayer> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NeuronLayer>() {
              public NeuronLayer findValueByNumber(int number) {
                return NeuronLayer.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return jwblangley.neat.proto.Genotypes.NeuronGenotype.getDescriptor().getEnumTypes().get(0);
      }

      private static final NeuronLayer[] VALUES = values();

      public static NeuronLayer valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NeuronLayer(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:jwblangley.neat.proto.NeuronGenotype.NeuronLayer)
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>int32 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }

    public static final int LAYER_FIELD_NUMBER = 2;
    private int layer_;
    /**
     * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
     * @return The enum numeric value on the wire for layer.
     */
    @java.lang.Override public int getLayerValue() {
      return layer_;
    }
    /**
     * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
     * @return The layer.
     */
    @java.lang.Override public jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer getLayer() {
      @SuppressWarnings("deprecation")
      jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer result = jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer.valueOf(layer_);
      return result == null ? jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (layer_ != jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer.INPUT.getNumber()) {
        output.writeEnum(2, layer_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (layer_ != jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer.INPUT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, layer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jwblangley.neat.proto.Genotypes.NeuronGenotype)) {
        return super.equals(obj);
      }
      jwblangley.neat.proto.Genotypes.NeuronGenotype other = (jwblangley.neat.proto.Genotypes.NeuronGenotype) obj;

      if (getUid()
          != other.getUid()) return false;
      if (layer_ != other.layer_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + LAYER_FIELD_NUMBER;
      hash = (53 * hash) + layer_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.NeuronGenotype parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jwblangley.neat.proto.Genotypes.NeuronGenotype prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jwblangley.neat.proto.NeuronGenotype}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jwblangley.neat.proto.NeuronGenotype)
        jwblangley.neat.proto.Genotypes.NeuronGenotypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NeuronGenotype_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NeuronGenotype_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jwblangley.neat.proto.Genotypes.NeuronGenotype.class, jwblangley.neat.proto.Genotypes.NeuronGenotype.Builder.class);
      }

      // Construct using jwblangley.neat.proto.Genotypes.NeuronGenotype.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0;

        layer_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_NeuronGenotype_descriptor;
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.NeuronGenotype getDefaultInstanceForType() {
        return jwblangley.neat.proto.Genotypes.NeuronGenotype.getDefaultInstance();
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.NeuronGenotype build() {
        jwblangley.neat.proto.Genotypes.NeuronGenotype result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.NeuronGenotype buildPartial() {
        jwblangley.neat.proto.Genotypes.NeuronGenotype result = new jwblangley.neat.proto.Genotypes.NeuronGenotype(this);
        result.uid_ = uid_;
        result.layer_ = layer_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jwblangley.neat.proto.Genotypes.NeuronGenotype) {
          return mergeFrom((jwblangley.neat.proto.Genotypes.NeuronGenotype)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jwblangley.neat.proto.Genotypes.NeuronGenotype other) {
        if (other == jwblangley.neat.proto.Genotypes.NeuronGenotype.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.layer_ != 0) {
          setLayerValue(other.getLayerValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jwblangley.neat.proto.Genotypes.NeuronGenotype parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jwblangley.neat.proto.Genotypes.NeuronGenotype) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>int32 uid = 1;</code>
       * @return The uid.
       */
      @java.lang.Override
      public int getUid() {
        return uid_;
      }
      /**
       * <code>int32 uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private int layer_ = 0;
      /**
       * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
       * @return The enum numeric value on the wire for layer.
       */
      @java.lang.Override public int getLayerValue() {
        return layer_;
      }
      /**
       * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
       * @param value The enum numeric value on the wire for layer to set.
       * @return This builder for chaining.
       */
      public Builder setLayerValue(int value) {
        
        layer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
       * @return The layer.
       */
      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer getLayer() {
        @SuppressWarnings("deprecation")
        jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer result = jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer.valueOf(layer_);
        return result == null ? jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer.UNRECOGNIZED : result;
      }
      /**
       * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
       * @param value The layer to set.
       * @return This builder for chaining.
       */
      public Builder setLayer(jwblangley.neat.proto.Genotypes.NeuronGenotype.NeuronLayer value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        layer_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.jwblangley.neat.proto.NeuronGenotype.NeuronLayer layer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLayer() {
        
        layer_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jwblangley.neat.proto.NeuronGenotype)
    }

    // @@protoc_insertion_point(class_scope:jwblangley.neat.proto.NeuronGenotype)
    private static final jwblangley.neat.proto.Genotypes.NeuronGenotype DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jwblangley.neat.proto.Genotypes.NeuronGenotype();
    }

    public static jwblangley.neat.proto.Genotypes.NeuronGenotype getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NeuronGenotype>
        PARSER = new com.google.protobuf.AbstractParser<NeuronGenotype>() {
      @java.lang.Override
      public NeuronGenotype parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NeuronGenotype(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NeuronGenotype> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NeuronGenotype> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.NeuronGenotype getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConnectionGenotypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jwblangley.neat.proto.ConnectionGenotype)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 neuronUidFrom = 1;</code>
     * @return The neuronUidFrom.
     */
    int getNeuronUidFrom();

    /**
     * <code>int32 neuronUidTo = 2;</code>
     * @return The neuronUidTo.
     */
    int getNeuronUidTo();

    /**
     * <code>int32 innovationMarker = 3;</code>
     * @return The innovationMarker.
     */
    int getInnovationMarker();

    /**
     * <code>double weight = 4;</code>
     * @return The weight.
     */
    double getWeight();

    /**
     * <code>bool enabled = 5;</code>
     * @return The enabled.
     */
    boolean getEnabled();
  }
  /**
   * Protobuf type {@code jwblangley.neat.proto.ConnectionGenotype}
   */
  public static final class ConnectionGenotype extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jwblangley.neat.proto.ConnectionGenotype)
      ConnectionGenotypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConnectionGenotype.newBuilder() to construct.
    private ConnectionGenotype(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectionGenotype() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConnectionGenotype();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConnectionGenotype(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              neuronUidFrom_ = input.readInt32();
              break;
            }
            case 16: {

              neuronUidTo_ = input.readInt32();
              break;
            }
            case 24: {

              innovationMarker_ = input.readInt32();
              break;
            }
            case 33: {

              weight_ = input.readDouble();
              break;
            }
            case 40: {

              enabled_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_ConnectionGenotype_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_ConnectionGenotype_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jwblangley.neat.proto.Genotypes.ConnectionGenotype.class, jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder.class);
    }

    public static final int NEURONUIDFROM_FIELD_NUMBER = 1;
    private int neuronUidFrom_;
    /**
     * <code>int32 neuronUidFrom = 1;</code>
     * @return The neuronUidFrom.
     */
    @java.lang.Override
    public int getNeuronUidFrom() {
      return neuronUidFrom_;
    }

    public static final int NEURONUIDTO_FIELD_NUMBER = 2;
    private int neuronUidTo_;
    /**
     * <code>int32 neuronUidTo = 2;</code>
     * @return The neuronUidTo.
     */
    @java.lang.Override
    public int getNeuronUidTo() {
      return neuronUidTo_;
    }

    public static final int INNOVATIONMARKER_FIELD_NUMBER = 3;
    private int innovationMarker_;
    /**
     * <code>int32 innovationMarker = 3;</code>
     * @return The innovationMarker.
     */
    @java.lang.Override
    public int getInnovationMarker() {
      return innovationMarker_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 4;
    private double weight_;
    /**
     * <code>double weight = 4;</code>
     * @return The weight.
     */
    @java.lang.Override
    public double getWeight() {
      return weight_;
    }

    public static final int ENABLED_FIELD_NUMBER = 5;
    private boolean enabled_;
    /**
     * <code>bool enabled = 5;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (neuronUidFrom_ != 0) {
        output.writeInt32(1, neuronUidFrom_);
      }
      if (neuronUidTo_ != 0) {
        output.writeInt32(2, neuronUidTo_);
      }
      if (innovationMarker_ != 0) {
        output.writeInt32(3, innovationMarker_);
      }
      if (weight_ != 0D) {
        output.writeDouble(4, weight_);
      }
      if (enabled_ != false) {
        output.writeBool(5, enabled_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (neuronUidFrom_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, neuronUidFrom_);
      }
      if (neuronUidTo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, neuronUidTo_);
      }
      if (innovationMarker_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, innovationMarker_);
      }
      if (weight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, weight_);
      }
      if (enabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, enabled_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jwblangley.neat.proto.Genotypes.ConnectionGenotype)) {
        return super.equals(obj);
      }
      jwblangley.neat.proto.Genotypes.ConnectionGenotype other = (jwblangley.neat.proto.Genotypes.ConnectionGenotype) obj;

      if (getNeuronUidFrom()
          != other.getNeuronUidFrom()) return false;
      if (getNeuronUidTo()
          != other.getNeuronUidTo()) return false;
      if (getInnovationMarker()
          != other.getInnovationMarker()) return false;
      if (java.lang.Double.doubleToLongBits(getWeight())
          != java.lang.Double.doubleToLongBits(
              other.getWeight())) return false;
      if (getEnabled()
          != other.getEnabled()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NEURONUIDFROM_FIELD_NUMBER;
      hash = (53 * hash) + getNeuronUidFrom();
      hash = (37 * hash) + NEURONUIDTO_FIELD_NUMBER;
      hash = (53 * hash) + getNeuronUidTo();
      hash = (37 * hash) + INNOVATIONMARKER_FIELD_NUMBER;
      hash = (53 * hash) + getInnovationMarker();
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWeight()));
      hash = (37 * hash) + ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnabled());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jwblangley.neat.proto.Genotypes.ConnectionGenotype prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jwblangley.neat.proto.ConnectionGenotype}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jwblangley.neat.proto.ConnectionGenotype)
        jwblangley.neat.proto.Genotypes.ConnectionGenotypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_ConnectionGenotype_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_ConnectionGenotype_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jwblangley.neat.proto.Genotypes.ConnectionGenotype.class, jwblangley.neat.proto.Genotypes.ConnectionGenotype.Builder.class);
      }

      // Construct using jwblangley.neat.proto.Genotypes.ConnectionGenotype.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        neuronUidFrom_ = 0;

        neuronUidTo_ = 0;

        innovationMarker_ = 0;

        weight_ = 0D;

        enabled_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jwblangley.neat.proto.Genotypes.internal_static_jwblangley_neat_proto_ConnectionGenotype_descriptor;
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.ConnectionGenotype getDefaultInstanceForType() {
        return jwblangley.neat.proto.Genotypes.ConnectionGenotype.getDefaultInstance();
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.ConnectionGenotype build() {
        jwblangley.neat.proto.Genotypes.ConnectionGenotype result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jwblangley.neat.proto.Genotypes.ConnectionGenotype buildPartial() {
        jwblangley.neat.proto.Genotypes.ConnectionGenotype result = new jwblangley.neat.proto.Genotypes.ConnectionGenotype(this);
        result.neuronUidFrom_ = neuronUidFrom_;
        result.neuronUidTo_ = neuronUidTo_;
        result.innovationMarker_ = innovationMarker_;
        result.weight_ = weight_;
        result.enabled_ = enabled_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jwblangley.neat.proto.Genotypes.ConnectionGenotype) {
          return mergeFrom((jwblangley.neat.proto.Genotypes.ConnectionGenotype)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jwblangley.neat.proto.Genotypes.ConnectionGenotype other) {
        if (other == jwblangley.neat.proto.Genotypes.ConnectionGenotype.getDefaultInstance()) return this;
        if (other.getNeuronUidFrom() != 0) {
          setNeuronUidFrom(other.getNeuronUidFrom());
        }
        if (other.getNeuronUidTo() != 0) {
          setNeuronUidTo(other.getNeuronUidTo());
        }
        if (other.getInnovationMarker() != 0) {
          setInnovationMarker(other.getInnovationMarker());
        }
        if (other.getWeight() != 0D) {
          setWeight(other.getWeight());
        }
        if (other.getEnabled() != false) {
          setEnabled(other.getEnabled());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jwblangley.neat.proto.Genotypes.ConnectionGenotype parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jwblangley.neat.proto.Genotypes.ConnectionGenotype) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int neuronUidFrom_ ;
      /**
       * <code>int32 neuronUidFrom = 1;</code>
       * @return The neuronUidFrom.
       */
      @java.lang.Override
      public int getNeuronUidFrom() {
        return neuronUidFrom_;
      }
      /**
       * <code>int32 neuronUidFrom = 1;</code>
       * @param value The neuronUidFrom to set.
       * @return This builder for chaining.
       */
      public Builder setNeuronUidFrom(int value) {
        
        neuronUidFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 neuronUidFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeuronUidFrom() {
        
        neuronUidFrom_ = 0;
        onChanged();
        return this;
      }

      private int neuronUidTo_ ;
      /**
       * <code>int32 neuronUidTo = 2;</code>
       * @return The neuronUidTo.
       */
      @java.lang.Override
      public int getNeuronUidTo() {
        return neuronUidTo_;
      }
      /**
       * <code>int32 neuronUidTo = 2;</code>
       * @param value The neuronUidTo to set.
       * @return This builder for chaining.
       */
      public Builder setNeuronUidTo(int value) {
        
        neuronUidTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 neuronUidTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeuronUidTo() {
        
        neuronUidTo_ = 0;
        onChanged();
        return this;
      }

      private int innovationMarker_ ;
      /**
       * <code>int32 innovationMarker = 3;</code>
       * @return The innovationMarker.
       */
      @java.lang.Override
      public int getInnovationMarker() {
        return innovationMarker_;
      }
      /**
       * <code>int32 innovationMarker = 3;</code>
       * @param value The innovationMarker to set.
       * @return This builder for chaining.
       */
      public Builder setInnovationMarker(int value) {
        
        innovationMarker_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 innovationMarker = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInnovationMarker() {
        
        innovationMarker_ = 0;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>double weight = 4;</code>
       * @return The weight.
       */
      @java.lang.Override
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>double weight = 4;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(double value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        
        weight_ = 0D;
        onChanged();
        return this;
      }

      private boolean enabled_ ;
      /**
       * <code>bool enabled = 5;</code>
       * @return The enabled.
       */
      @java.lang.Override
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>bool enabled = 5;</code>
       * @param value The enabled to set.
       * @return This builder for chaining.
       */
      public Builder setEnabled(boolean value) {
        
        enabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool enabled = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabled() {
        
        enabled_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jwblangley.neat.proto.ConnectionGenotype)
    }

    // @@protoc_insertion_point(class_scope:jwblangley.neat.proto.ConnectionGenotype)
    private static final jwblangley.neat.proto.Genotypes.ConnectionGenotype DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jwblangley.neat.proto.Genotypes.ConnectionGenotype();
    }

    public static jwblangley.neat.proto.Genotypes.ConnectionGenotype getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConnectionGenotype>
        PARSER = new com.google.protobuf.AbstractParser<ConnectionGenotype>() {
      @java.lang.Override
      public ConnectionGenotype parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConnectionGenotype(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectionGenotype> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectionGenotype> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jwblangley.neat.proto.Genotypes.ConnectionGenotype getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jwblangley_neat_proto_NetworkGenotype_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jwblangley_neat_proto_NetworkGenotype_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jwblangley_neat_proto_NeuronGenotype_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jwblangley_neat_proto_NeuronGenotype_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jwblangley_neat_proto_ConnectionGenotype_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jwblangley_neat_proto_ConnectionGenotype_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/jwblangley/neat/proto/genotypes.pr" +
      "oto\022\025jwblangley.neat.proto\"\211\001\n\017NetworkGe" +
      "notype\0226\n\007neurons\030\001 \003(\0132%.jwblangley.nea" +
      "t.proto.NeuronGenotype\022>\n\013connections\030\002 " +
      "\003(\0132).jwblangley.neat.proto.ConnectionGe" +
      "notype\"\221\001\n\016NeuronGenotype\022\013\n\003uid\030\001 \001(\005\022@" +
      "\n\005layer\030\002 \001(\01621.jwblangley.neat.proto.Ne" +
      "uronGenotype.NeuronLayer\"0\n\013NeuronLayer\022" +
      "\t\n\005INPUT\020\000\022\n\n\006HIDDEN\020\001\022\n\n\006OUTPUT\020\002\"{\n\022Co" +
      "nnectionGenotype\022\025\n\rneuronUidFrom\030\001 \001(\005\022" +
      "\023\n\013neuronUidTo\030\002 \001(\005\022\030\n\020innovationMarker" +
      "\030\003 \001(\005\022\016\n\006weight\030\004 \001(\001\022\017\n\007enabled\030\005 \001(\010b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_jwblangley_neat_proto_NetworkGenotype_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jwblangley_neat_proto_NetworkGenotype_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jwblangley_neat_proto_NetworkGenotype_descriptor,
        new java.lang.String[] { "Neurons", "Connections", });
    internal_static_jwblangley_neat_proto_NeuronGenotype_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jwblangley_neat_proto_NeuronGenotype_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jwblangley_neat_proto_NeuronGenotype_descriptor,
        new java.lang.String[] { "Uid", "Layer", });
    internal_static_jwblangley_neat_proto_ConnectionGenotype_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_jwblangley_neat_proto_ConnectionGenotype_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jwblangley_neat_proto_ConnectionGenotype_descriptor,
        new java.lang.String[] { "NeuronUidFrom", "NeuronUidTo", "InnovationMarker", "Weight", "Enabled", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
